version: '3'

services:
  backend:
    image: relatives_backend:latest
    container_name: relatives_backend
    build:
      context: .
      dockerfile: src/backend/docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./relatives.db:/app/relatives.db
    ports:
      - "443:8000"
    profiles:
      - prod
