version: '3.8'

x-env-defaults: &defaults
  env_file: .env
  restart: unless-stopped

services:
  backend:
    <<: *defaults
    image: relatives_backend:latest
    container_name: relatives_backend
    build:
      context: .
      dockerfile: src/backend/docker/Dockerfile
    volumes:
      # why not copied from container?
      #- ./static/:/app/static/
      - ./relatives.db:/app/relatives.db
    ports:
      - "9000:8000"

  postgres:
    <<: *defaults
    image: bitnami/postgresql:15
    environment:
      POSTGRESQL_DATABASE: $DB_NAME
      POSTGRESQL_USERNAME: $DB_USER
      POSTGRESQL_PASSWORD: $DB_PASS
    expose:
      - 5432
    volumes:
      - ./postgresql:/bitnami/postgresql
