version: '3'

services:
  backend:
    image: relatives_backend:latest
    container_name: relatives_backend
    build:
      context: .
      dockerfile: src/backend/docker/Dockerfile
    env_file:
      - .env
    volumes:
      # why not copied from container?
      #- ./static/:/app/static/
      - ./relatives.db:/app/relatives.db
    ports:
      - "9000:8000"
    restart: unless-stopped
