name: CI/CD

run-name: ${{ github.actor }} pushed changes

on:
  push:
  pull_request:
    branches: [ main ]

env:
  DB_HOST: "localhost"
  DB_NAME: "test"
  DB_USER: "postgres"
  DB_PASS: "postgres"

jobs:
  CI:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
        poetry-version: [ "1.2" ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: bitnami/postgresql:15
        env:
          POSTGRESQL_DATABASE: test
          POSTGRESQL_USERNAME: postgres
          POSTGRESQL_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install --no-cache
      - name: Run linters
        run: make style
      - name: Apply migrations
        run: make migrate
      - name: Run tests
        run: make test
        env:
          STATIC_DIR: "src/backend/static"
          TEMPLATES_DIR: "src/backend/templates"
          MAIL_SUPPRESS: 1
